### ISSUE TITLE
Links quebrados 

### ISSUE THREAD

**Issue by RennanSilvaCosta** [yurimutti/recursosfrontend#12]
Eu estava verificando a integridade dos links, e encontrei alguns que aparentemente estão quebrados. Estou tentando descobrir o porque deles não estarem redirecionando para o site. Aparentemente o link para o site está correto. Porém ao clicar neles acontece o seguinte: 

![block](https://user-images.githubusercontent.com/45303056/117226432-094ea180-adeb-11eb-9fcf-d223496e239f.PNG)
![block2](https://user-images.githubusercontent.com/45303056/117226491-25ead980-adeb-11eb-8a11-40fdcb317afb.PNG)

Testei em alguns navegadores, OperaGX, Google Chrome e Firefox. O resultado foi o mesmo em todos.

Links quebrados: 
* [⁣abduzeedo⁣](https://⁣abduzeedo.com⁣)  
* ⁣⁣⁣[⁣⁣⁣Best Website Gallery⁣](https://⁣⁣bestwebsite.gallery⁣)
* [Commercecream.com⁣](https://commercecream.com⁣)  
* [Css Nectar](https://cssnectar.com⁣)  
* [Land-book](https://land-book.com⁣)

**Comment by yurimutti** [comment]
Verdade, bem estranho, os links estão bons.

**Comment by RennanSilvaCosta** [comment]
Dessa vez eu abri o README na IDEA que eu uso, o intellij, e apareceu uma coisa interessante: 
![error](https://user-images.githubusercontent.com/45303056/118576526-13638f00-b75f-11eb-9b1b-804c4c4008dd.PNG)
![error2](https://user-images.githubusercontent.com/45303056/118576573-2aa27c80-b75f-11eb-97f7-f5493daaaa7f.PNG)

Os links que eu apontei como quebrados estão com uma espécie de virgula.
Quando eu retiro esses caracteres o link volta a funcionar normalmente.

Fiz uma pequena busca e descobri que esse caractere é um 'separador invisível":
font: https://unicodes.jessetane.com/%E2%81%A3
![separator invisible](https://user-images.githubusercontent.com/45303056/118578186-16ac4a00-b762-11eb-8ed3-c435a7752da9.PNG)

Verifiquei o histórico de commits e observei que esses links foram inseridos no dia 19 de Janeiro, e já estavam com o separador invisível no link, pois não encontrei mais nenhuma alteração nesses links, após o commit do dia 19 de Janeiro.

Para Ilustrar, fiz um vídeo mostrando o problema: [video](https://www.youtube.com/watch?v=yF0_F8iY4NU)

Vou remover todos os separadores invisíveis e enviar as alterações.

**Comment by RennanSilvaCosta** [comment]
Fiz uma pequena busca e descobri que esse caractere é um 'separador invisível":
font: https://unicodes.jessetane.com/%E2%81%A3
![separator invisible](https://user-images.githubusercontent.com/45303056/118578186-16ac4a00-b762-11eb-8ed3-c435a7752da9.PNG)

Verifiquei o histórico de commits e observei que esses links foram inseridos no dia 19 de Janeiro, e já estavam com o separador invisível no link.
Bom aparentemente esses links já estavam com o separador vazio quando foram inseridos, pois não encontrei mais nenhuma alteração nesses links, após o commit do dia 19 de Janeiro.
Para Ilustrar, fiz um vídeo mostrando o problema: [video](https://www.youtube.com/watch?v=yF0_F8iY4NU)

Vou remover todos os separadores invisíveis que encontrar e enviar as alterações.

**Comment by yurimutti** [comment]
Interessante, nunca tinha visto isso, show man!!
