### ISSUE TITLE
Estrutura do readme

### ISSUE THREAD

**Issue by RennanSilvaCosta** [yurimutti/recursosfrontend#14]
Estava pensando em alterar a estrutura do readme.
Primeiro exibindo um índice com as "categorias". Após o índice, exibir os links em forma de tabela, com três colunas: "Link, Descrição, Grátis". Da seguinte forma: 

O que acha?

![estrutura](https://user-images.githubusercontent.com/45303056/119277503-7be6bc00-bbf6-11eb-87a9-be5edfa6e736.PNG)

**Comment by yurimutti** [comment]
Acho uma ótima ideia,vamos nessa!! Vou complementar e fazer uma seção de colaboradores  com um destaque maior no rodapé.

**Comment by RennanSilvaCosta** [comment]
Maravilha, acha melhor fazer em Markdown ou html?
